ZSTD_COMPRESSION_LEVEL = 3
MAX_FAILURES_BEFORE_DEPRECATION = 3
DEPRECATED_VACUUM_MAX_AGE_DAYS = 30
DEFAULT_TOP_K_RETRIEVAL = 3
MIN_SUCCESS_COUNT_FOR_RETRIEVAL = 0
STALENESS_HALF_LIFE_DAYS = 7.0
AUDIT_LOG_RETENTION_DAYS = 90
